theme: jekyll-theme-cayman
title: [Know-Lib]
description: [Just a digital library containing information I gathered while studying a bit of everything]
google_analytics: [Your Google Analytics tracking ID]